webtalk_init -webtalk_dir C:/Users/daksh/Documents/Academic/Semester 2/Practicals/Computer Architecture/Lab 01/Lab 9-10/Lab 9-10.sim/sim_1/behav/xsim/xsim.dir/Instruction_Decoder_Sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 29 17:14:58 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fc28aa441cec5baabe87848e8db33830" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "52dcb91c77fa4d91b387034ee4c96723" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6244_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1250931484 -regid "" -xml C:/Users/daksh/Documents/Academic/Semester 2/Practicals/Computer Architecture/Lab 01/Lab 9-10/Lab 9-10.sim/sim_1/behav/xsim/xsim.dir/Instruction_Decoder_Sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/daksh/Documents/Academic/Semester 2/Practicals/Computer Architecture/Lab 01/Lab 9-10/Lab 9-10.sim/sim_1/behav/xsim/xsim.dir/Instruction_Decoder_Sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/daksh/Documents/Academic/Semester 2/Practicals/Computer Architecture/Lab 01/Lab 9-10/Lab 9-10.sim/sim_1/behav/xsim/xsim.dir/Instruction_Decoder_Sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
